/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__base
#define __PYX_HAVE__base


#ifndef __PYX_HAVE_API__base

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(DWORD) CONTEXT_ALL;

#endif /* !__PYX_HAVE_API__base */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initbase(void);
#else
PyMODINIT_FUNC PyInit_base(void);
#endif

#endif /* !__PYX_HAVE__base */
