from error cimport *

cdef public DWORD ERROR_SUCCESS
cdef public DWORD ERROR_INSUFFICIENT_BUFFER
cdef public DWORD ERROR_INVALID_TASK_NAME
cdef public DWORD ERROR_INVALID_TASK_INDEX
cdef public DWORD ERROR_PRIVILEGE_NOT_HELD
