/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__error
#define __PYX_HAVE__error


#ifndef __PYX_HAVE_API__error

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(DWORD) __pyx_v_5error_ERROR_SUCCESS;
__PYX_EXTERN_C DL_IMPORT(DWORD) __pyx_v_5error_ERROR_INSUFFICIENT_BUFFER;

#endif /* !__PYX_HAVE_API__error */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initerror(void);
#else
PyMODINIT_FUNC PyInit_error(void);
#endif

#endif /* !__PYX_HAVE__error */
